# Generated by Django 5.0.2 on 2024-02-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='username',
            new_name='nickname',
        ),
    ]
