# Generated by Django 5.0.2 on 2024-02-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='damage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=5),
        ),
    ]
