# Generated by Django 5.0.2 on 2024-02-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_agility_character_armor_character_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
