# Generated by Django 5.0.2 on 2024-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='nickname',
            field=models.CharField(max_length=10),
        ),
    ]
