# Generated by Django 5.0.2 on 2024-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
