# Generated by Django 5.0.2 on 2024-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
    ]
