# Generated by Django 5.0.2 on 2024-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_character_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=1000),
        ),
    ]
