# Generated by Django 5.0.2 on 2024-03-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
