# Generated by Django 5.0.2 on 2024-03-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
