# Generated by Django 5.0.2 on 2024-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_monster_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='base_gold_gained',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
