# Generated by Django 5.0.2 on 2024-04-15 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_clicks_required',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='gold_to_gain',
            field=models.IntegerField(),
        ),
    ]
